name: Node.js CI

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "master"

jobs:
  check-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/erbium", "lts/fermium", lts/gallium, lts/hydrogen]

    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: npm install

      - name: Check linting
        run: npm run lint
