name: NodeJS CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["lts/gallium", "lts/hydrogen"]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: yarn install

      - name: Check linting
        run: yarn lint
